name: Docker

on:
  push:
    branches:
      - "main"

    paths-ignore:
      - "docs/**"
      - ".vscode/**"
      - ".git*"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/gh-pages.yml"
      - ".github/workflows/release.yml"

    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - "main"

    paths-ignore:
      - "docs/**"
      - ".vscode/**"
      - ".git*"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/gh-pages.yml"
      - ".github/workflows/release.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            branch=main,value=latest
            type=pep440,pattern={{version}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
