name: Create draft release

on:
  push:
    tags:
      - v*.*.*

  pull_request:
    branches:
      - main

    paths-ignore:
      - "docs/**"
      - ".vscode/**"
      - ".git*"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
      - ".dockerignore"
      - "Dockerfile"
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/publish-docker.yml"
      - ".github/workflows/gh-pages.yml"

jobs:
  format-check:
    name: Check correct formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1.2.1
        with:
          args: --recursive --diff --aggressive --aggressive noaa/**/*.py

      - name: Fail if autopep8 finds changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1

  lint-check:
    name: Check correct lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint>=2.5

      - name: Analysing the code with pylint
        run: |
          pylint --errors-only --py-version=3.7 --rcfile=pyproject.toml noaa

  coverage-check:
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "coverage[toml]>=6.0,<7.0"

      - name: Run coverage
        run: |
          python -m coverage run tests/climate.py ${{ secrets.CDO_TOKEN }}
          python -m coverage xml

      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/xml/
          files: coverage.xml
          flags: unittests
          name: codecov-noaa
          fail_ci_if_error: true
          verbose: true

  test:
    name: Test module on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install module on ${{ matrix.python-version }}
        run: |
          python -m pip install .

      - name: Run test on ${{ matrix.python-version }}
        run: |
          python tests/climate.py ${{ secrets.CDO_TOKEN }}

  draft:
    if: github.event_name != 'pull_request'
    name: Create draft
    needs: [format-check, lint-check, coverage-check, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    if: github.event_name != 'pull_request'
    name: Build wheel and fix to draft
    needs: draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.7"

      - name: Update dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel of noaa
        run: python -m pip wheel --use-pep517 --wheel-dir wheels/ .

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=pep440,pattern={{version}}

      - name: Set tag var
        id: tag
        run: echo ::set-output name=pip_tag::$(echo ${{ steps.meta.outputs.tags }} | awk '{ print substr ($0, 3 ) }')

      - name: Upload and attach release asset to draft
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.draft.outputs.upload_url }}
          asset_path: ./wheels/noaa-${{ steps.tag.outputs.pip_tag }}-py3-none-any.whl
          asset_name: noaa-${{ steps.tag.outputs.pip_tag }}-py3-none-any.whl
          asset_content_type: application/zip
